# Generated by Django 6.0.4 on 2026-05-06 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('role', models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer')], max_length=20)),
                ('monthly_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('yearly_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monthly_ugx', models.IntegerField(default=0)),
                ('yearly_ugx', models.IntegerField(default=0)),
                ('max_applications', models.IntegerField(default=5, help_text='-1 = unlimited')),
                ('max_job_posts', models.IntegerField(default=0, help_text='0 = N/A (jobseeker plan)')),
                ('is_featured_posts', models.BooleanField(default=False)),
                ('cv_storage', models.BooleanField(default=False)),
                ('direct_messaging', models.BooleanField(default=False)),
                ('analytics', models.BooleanField(default=False)),
                ('priority_listing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
