# Generated by Django 6.0.4 on 2026-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='currency_paid',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='gateway',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('stripe', 'Stripe (Card)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='gateway_ref',
            field=models.CharField(blank=True, help_text='MTN/Airtel reference_id or Stripe session_id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='gateway_txn_id',
            field=models.CharField(blank=True, help_text='Final transaction ID after payment confirmed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_job_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial'), ('pending', 'Pending Payment')], default='pending', max_length=20),
        ),
    ]
